version: '3'

services:
  web:
    build: ./api
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./api/app:/app

  mongo:
    image: mongo:latest
    ports: 
      - 27017:27017
    restart: always