version: '3'

services:
  web:
    restart: always
    build: ./api
    expose:
      - "8000"
    # links:
    #   - postgres:postgres
    volumes:
      - web-data:/usr/src/app/static
    # env_file: 
    #   - .env
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - .:/www/static
      - web-data:/usr/src/app/static
    links:
      - web:api

  mongodb:
    image: mongo:latest
    container_name: "mongodb"

volumes:
  db-data:
  web-data: